// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCZUJbyb2lVokIM_hxIVlFjdjW9M35Yv8',
    appId: '1:1032793914213:web:da2b91df1575aeb4eb3f8c',
    messagingSenderId: '1032793914213',
    projectId: 'dmf-n1lbr',
    authDomain: 'dmf-n1lbr.firebaseapp.com',
    storageBucket: 'dmf-n1lbr.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-Cn4xvAvrV5w9xntuQB8aXs3GAcCnnOQ',
    appId: '1:1032793914213:android:85d7db45cd9e7bfbeb3f8c',
    messagingSenderId: '1032793914213',
    projectId: 'dmf-n1lbr',
    storageBucket: 'dmf-n1lbr.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDIA_f_IVoKcGup7KveHxoFkAV3dsIDZs',
    appId: '1:1032793914213:ios:83c671eaa1548cfbeb3f8c',
    messagingSenderId: '1032793914213',
    projectId: 'dmf-n1lbr',
    storageBucket: 'dmf-n1lbr.appspot.com',
    iosBundleId: 'br.jbrnetwork.autoControlPanel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDIA_f_IVoKcGup7KveHxoFkAV3dsIDZs',
    appId: '1:1032793914213:ios:b81ecb3a1530f8daeb3f8c',
    messagingSenderId: '1032793914213',
    projectId: 'dmf-n1lbr',
    storageBucket: 'dmf-n1lbr.appspot.com',
    iosBundleId: 'com.example.autoControlPanel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBCZUJbyb2lVokIM_hxIVlFjdjW9M35Yv8',
    appId: '1:1032793914213:web:18c0fe07ea91cdcceb3f8c',
    messagingSenderId: '1032793914213',
    projectId: 'dmf-n1lbr',
    authDomain: 'dmf-n1lbr.firebaseapp.com',
    storageBucket: 'dmf-n1lbr.appspot.com',
  );

}